pipeline {
    agent any
    
    stages {
        
        stage('Initialize') {
            steps {
                export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

                export M2_HOME=/opt/maven

                export MAVEN_HOME=/opt/maven
            }
        }
        
        stage('Build') {
            steps {
                
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
