pipeline {
    agent any
    tools {
     maven 'MavenAlreadyInstalled3.8.5'   
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'In Deliver Stage.....'
                sh 'cp target/mywebwar /opt/tomcat10/webapps/'
                sh '/opt/tomcat10/bin/shutdown.sh'
                sh '/opt/tomcat10/bin/starup.sh'
                
            }
        }
    }
}
